# Generated by Django 5.1 on 2024-08-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_name', models.CharField(max_length=50, null=True)),
                ('armor_description', models.TextField(default='')),
                ('armor_bonus', models.SmallIntegerField(default=0)),
                ('armor_type', models.CharField(max_length=50, null=True)),
                ('armor_check_penalty', models.SmallIntegerField(default=0)),
                ('armor_spell_fail', models.SmallIntegerField(default=0)),
                ('armor_weight', models.PositiveSmallIntegerField(default=0)),
                ('armor_properties', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=50, null=True)),
                ('attr_base', models.PositiveSmallIntegerField(default=10)),
                ('attr_adj', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('class_bab', models.SmallIntegerField(default=0)),
                ('class_will_mod', models.PositiveSmallIntegerField(default=0)),
                ('class_fort_mod', models.PositiveSmallIntegerField(default=0)),
                ('class_level', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DamageResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg_res_name', models.CharField(max_length=50, null=True)),
                ('dmg_res_type', models.CharField(max_length=20, null=True)),
                ('dmg_res_value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_trait', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constitution'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma'), ('attack', 'Attack'), ('cmd', 'CMD'), ('cmb', 'CMB'), ('size', 'Size'), ('spell_res', 'Spell Resistance'), ('damage_res', 'Damage Resistance'), ('ac', 'Armor Class'), ('move_speed', 'Movement Speed'), ('init_misc', 'Initiative')], max_length=50, null=True)),
                ('effect_value', models.SmallIntegerField(default=0)),
                ('effect_condition', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('item_description', models.TextField(default='')),
                ('item_weight', models.PositiveSmallIntegerField(default=0)),
                ('item_amount', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_name', models.CharField(max_length=50, null=True)),
                ('save_magic', models.SmallIntegerField(default=0)),
                ('save_temp', models.SmallIntegerField(default=0)),
                ('save_misc', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, null=True)),
                ('skill_ranks', models.PositiveSmallIntegerField(default=0)),
                ('skill_mod', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpellCasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_level', models.PositiveSmallIntegerField(null=True)),
                ('spell_save_dc', models.PositiveSmallIntegerField(null=True)),
                ('spells_known', models.PositiveSmallIntegerField(null=True)),
                ('spells_per_day', models.PositiveSmallIntegerField(null=True)),
                ('bonus_spells', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=50, null=True)),
                ('spell_description', models.TextField(default='')),
                ('spell_level', models.PositiveSmallIntegerField(null=True)),
                ('spell_school', models.CharField(max_length=50, null=True)),
                ('spell_components', models.CharField(max_length=100, null=True)),
                ('spell_range', models.CharField(max_length=50, null=True)),
                ('spell_target', models.CharField(max_length=100, null=True)),
                ('spell_duration', models.CharField(max_length=50, null=True)),
                ('spell_saving_throw', models.CharField(max_length=50, null=True)),
                ('spell_resistance', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=50, null=True)),
                ('weapon_description', models.TextField(default='')),
                ('weapon_attack_bonus', models.PositiveSmallIntegerField(default=0)),
                ('weapon_crit_range', models.PositiveSmallIntegerField(default=20)),
                ('weapon_crit_damage', models.PositiveSmallIntegerField(default=2)),
                ('weapon_range', models.PositiveSmallIntegerField(default=5)),
                ('weapon_ammunition', models.PositiveSmallIntegerField(null=True)),
                ('weapon_damage_dice', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_name', models.CharField(max_length=50, null=True)),
                ('feat_description', models.TextField(default='')),
                ('feat_source', models.CharField(max_length=50, null=True)),
                ('feat_effect', models.ManyToManyField(to='characters.effect')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=50, null=True)),
                ('ability_description', models.TextField(default='')),
                ('ability_source', models.CharField(max_length=50, null=True)),
                ('ability_effect', models.ManyToManyField(to='characters.effect')),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=50, null=True)),
                ('trait_description', models.TextField(default='')),
                ('trait_effect', models.ManyToManyField(to='characters.effect')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('player', models.CharField(default='Player', max_length=100)),
                ('race', models.CharField(max_length=50, null=True)),
                ('alignment', models.CharField(max_length=20, null=True)),
                ('deity', models.CharField(max_length=100, null=True)),
                ('homeland', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(null=True)),
                ('hair', models.CharField(max_length=100, null=True)),
                ('eyes', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(default='medium', max_length=20)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('char_save_mod_general', models.SmallIntegerField(default=0)),
                ('spell_resistance', models.SmallIntegerField(default=0)),
                ('dmg_res_general', models.PositiveSmallIntegerField(default=0)),
                ('total_hit_points', models.PositiveSmallIntegerField(null=True)),
                ('current_hit_points', models.SmallIntegerField(null=True)),
                ('temporary_hit_points', models.SmallIntegerField(default=0)),
                ('non_lethal_dmg', models.PositiveSmallIntegerField(null=True)),
                ('base_armor', models.PositiveSmallIntegerField(default=10)),
                ('size_armor', models.SmallIntegerField(default=0)),
                ('natural_armor', models.SmallIntegerField(default=0)),
                ('deflection_armor', models.SmallIntegerField(default=0)),
                ('initiative_misc', models.SmallIntegerField(default=0)),
                ('cmb_modifier', models.SmallIntegerField(null=True)),
                ('cmd_modifier', models.SmallIntegerField(null=True)),
                ('bab_general_modifiers', models.SmallIntegerField(default=0)),
                ('armor', models.ManyToManyField(to='characters.armors')),
                ('char_attributes', models.ManyToManyField(to='characters.attributes')),
                ('char_classes', models.ManyToManyField(to='characters.characterclass')),
                ('dmg_resistance', models.ManyToManyField(to='characters.damageresistance')),
                ('feats', models.ManyToManyField(to='characters.feats')),
                ('inventory', models.ManyToManyField(to='characters.items')),
                ('char_saving_throws', models.ManyToManyField(to='characters.savingthrows')),
                ('char_skills', models.ManyToManyField(to='characters.skills')),
                ('special_abilities', models.ManyToManyField(to='characters.specialabilities')),
                ('spell_casting', models.ManyToManyField(to='characters.spellcasting')),
                ('spells', models.ManyToManyField(to='characters.spells')),
                ('traits', models.ManyToManyField(to='characters.traits')),
                ('weapon', models.ManyToManyField(to='characters.weapons')),
            ],
        ),
    ]
